//! Real third-party Winamp target downloaded during the Aether build.
//! The executable is not generated by Aether; CI downloads the official Winamp
//! installer and extracts its real winamp.exe before compiling the kernel.

pub fn install() -> bool {
    crate::fs::write_large("/winamp.exe", crate::winamp_builtin::WINAMP_EXE)
}

#[derive(Clone, Copy)]
pub struct Diagnostic {
    pub file_found: bool,
    pub header_bytes: usize,
    pub mz_valid: bool,
    pub pe_valid: bool,
    pub pe_offset: u32,
    pub machine: u16,
    pub sections: u16,
    pub optional_size: u16,
    pub optional_magic: u16,
    pub pe32_x86: bool,
}

fn read16(b: &[u8], p: usize) -> u16 {
    (b[p] as u16) | ((b[p + 1] as u16) << 8)
}

fn read32(b: &[u8], p: usize) -> u32 {
    (b[p] as u32)
        | ((b[p + 1] as u32) << 8)
        | ((b[p + 2] as u32) << 16)
        | ((b[p + 3] as u32) << 24)
}

pub fn diagnose() -> Diagnostic {
    let mut b = [0u8; 512];
    let n = match crate::fs::read_large("/winamp.exe", &mut b) {
        Some(n) => n,
        None => {
            return Diagnostic {
                file_found: false, header_bytes: 0, mz_valid: false, pe_valid: false,
                pe_offset: 0, machine: 0, sections: 0, optional_size: 0,
                optional_magic: 0, pe32_x86: false,
            }
        }
    };

    let mz = n >= 2 && b[0] == b'M' && b[1] == b'Z';
    if !mz || n < 0x40 {
        return Diagnostic {
            file_found: true, header_bytes: n, mz_valid: mz, pe_valid: false,
            pe_offset: 0, machine: 0, sections: 0, optional_size: 0,
            optional_magic: 0, pe32_x86: false,
        };
    }

    let pe_offset = read32(&b, 0x3c);
    let p = pe_offset as usize;
    if p + 24 > n {
        return Diagnostic {
            file_found: true, header_bytes: n, mz_valid: true, pe_valid: false,
            pe_offset, machine: 0, sections: 0, optional_size: 0,
            optional_magic: 0, pe32_x86: false,
        };
    }

    let pe = b[p] == b'P' && b[p + 1] == b'E' && b[p + 2] == 0 && b[p + 3] == 0;
    if !pe {
        return Diagnostic {
            file_found: true, header_bytes: n, mz_valid: true, pe_valid: false,
            pe_offset, machine: 0, sections: 0, optional_size: 0,
            optional_magic: 0, pe32_x86: false,
        };
    }

    let machine = read16(&b, p + 4);
    let sections = read16(&b, p + 6);
    let optional_size = read16(&b, p + 20);
    let optional_magic = if p + 26 <= n { read16(&b, p + 24) } else { 0 };
    let pe32_x86 = machine == 0x014c
        && sections > 0
        && optional_size == 0xE0
        && optional_magic == 0x10B;

    Diagnostic {
        file_found: true,
        header_bytes: n,
        mz_valid: true,
        pe_valid: true,
        pe_offset,
        machine,
        sections,
        optional_size,
        optional_magic,
        pe32_x86,
    }
}

pub fn launch() -> bool {
    let d = diagnose();
    let ok = d.pe32_x86;
    if ok {
        crate::serial::write_str("[WIN32] real Winamp.exe PE32/x86 recognized; safe compatibility window\n");
    } else {
        crate::serial::write_str("[WIN32] Winamp.exe PE32/x86 validation FAILED\n");
    }
    ok
}
