//! Real third-party Winamp target downloaded during the Aether build.
//! The executable is not generated by Aether; CI downloads the official Winamp
//! installer and extracts its real winamp.exe before compiling the kernel.

pub fn install() -> bool {
    crate::fs::write_large("/winamp.exe", crate::winamp_builtin::WINAMP_EXE)
}

pub fn launch() -> bool {
    crate::pe::launch_winamp()
}
